repos:
  - repo: local
    hooks:
      - id: terraform-format-and-docs
        name: Terraform Format and Docs
        entry: scripts/format-and-update.sh
        language: script
        pass_filenames: false
      - id: terragrunt-hclfmt
        name: Terragrunt hclfmt
        entry: scripts/terragrunt-hclfmt.sh
        language: script
        pass_filenames: false
